[Build]
CacheDirectory=mkosi.cache

[Distribution]
Distribution=debian
Release=forky

[Output]
Format=tar
Output=%d-%r_%a
CompressOutput=xz
OutputDirectory=mkosi.output

[Content]
Packages=
        systemd
