[Build]
CacheDirectory=mkosi.cache

[Distribution]
RepositoryKeyFetch=yes

[Output]
Format=tar
Output=%d-%r_%a
CompressOutput=xz
OutputDirectory=mkosi.output

[Content]
Bootable=no
RootPassword=hashed:!locked
