name: Build and Release Debian testing

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        arch: [x86-64, arm64]
        include:
          - arch: x86-64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
      fail-fast: false
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Print kernel version
        run: uname -r

      - name: Set up mkosi
        uses: systemd/mkosi@main

      - name: Checkout
        uses: actions/checkout@v7

      - name: Build image
        run: mkosi --debug
