name: Build and Release

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        target:
          - distro: debian
            release: trixie
          - distro: debian
            release: forky
          - distro: debian
            release: sid
          - distro: fedora
            release: 44
          - distro: fedora
            release: rawhide
        arch: [x86-64, arm64]
        include:
          - arch: x86-64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    container:
      image: quay.io/fedora/fedora-minimal:44
      options: --privileged

    steps:
      - name: Install base dependencies
        run: dnf -y install apt debian-keyring distribution-gpg-keys python3 tar xz

      - name: Checkout
        uses: actions/checkout@v7

      - name: Checkout mkosi
        uses: actions/checkout@v7
        with:
          repository: systemd/mkosi
          path: mkosi

      - name: Install mkosi
        run: ln -s $PWD/mkosi/bin/mkosi /usr/local/bin/mkosi

      - name: Install mkosi dependencies
        run: mkosi dependencies | xargs -d '\n' dnf -y install

      - name: Check mkosi version
        run: mkosi --version

      - name: Build image
        run: mkosi -d ${{ matrix.target.distro }} -r ${{ matrix.target.release }}

      - name: Generate checksum file
        run: for f in *.*; do sha256sum $f > $f.sha256; done
        working-directory: mkosi.output

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target.distro }}-${{ matrix.target.release }}_${{ matrix.arch }}
          path: mkosi.output/*.*
          if-no-files-found: error
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Create release
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete latest --cleanup-tag -y || true
          gh release create latest artifacts/* -t $(date -u +%F)
